#-----------------------------------------------------------------------------
# NanoSoC Test: uart_tests
# UART peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := uart_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
