#-----------------------------------------------------------------------------
# NanoSoC Test: uart_tests
# UART peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := uart_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
