#-----------------------------------------------------------------------------
# NanoSoC Test: watchdog_demo
# Watchdog timer demonstration
#-----------------------------------------------------------------------------
TESTNAME   := watchdog_demo
SOURCE_DIR  = $(SOFTWARE_DIR)/common/demos

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
