#-----------------------------------------------------------------------------
# NanoSoC Test: watchdog_demo
# Watchdog timer demonstration
#-----------------------------------------------------------------------------
TESTNAME   := watchdog_demo
SOURCE_DIR  = $(SOFTWARE_DIR)/common/demos

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
