#-----------------------------------------------------------------------------
# NanoSoC Test: memory_tests
# Memory subsystem validation tests
#-----------------------------------------------------------------------------
TESTNAME   := memory_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
