#-----------------------------------------------------------------------------
# NanoSoC Test: hello
# Simple hello world test - prints to UART via retarget
#-----------------------------------------------------------------------------
TESTNAME := hello

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
