#-----------------------------------------------------------------------------
# NanoSoC Test: hello
# Simple hello world test - prints to UART via retarget
#-----------------------------------------------------------------------------
TESTNAME := hello

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
