#-----------------------------------------------------------------------------
# NanoSoC Test: gpio_tests
# GPIO peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := gpio_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
