#-----------------------------------------------------------------------------
# NanoSoC Test: gpio_tests
# GPIO peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := gpio_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
