#-----------------------------------------------------------------------------
# NanoSoC Test: default_slaves_tests
# Default slave validation tests
#-----------------------------------------------------------------------------
TESTNAME   := default_slaves_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
