#-----------------------------------------------------------------------------
# NanoSoC Test: default_slaves_tests
# Default slave validation tests
#-----------------------------------------------------------------------------
TESTNAME   := default_slaves_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
