#-----------------------------------------------------------------------------
# NanoSoC Test: interrupt_demo
# Interrupt handling demonstration
#-----------------------------------------------------------------------------
TESTNAME      := interrupt_demo
SOURCE_DIR     = $(SOFTWARE_DIR)/common/demos
SOURCE_FILES  += $(DEVICE_DIR)/Source/CMSDK_driver.c

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
