#-----------------------------------------------------------------------------
# NanoSoC Test: interrupt_demo
# Interrupt handling demonstration
#-----------------------------------------------------------------------------
TESTNAME      := interrupt_demo
SOURCE_DIR     = $(SOFTWARE_DIR)/common/demos
SOURCE_FILES  += $(DEVICE_DIR)/Source/CMSDK_driver.c

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
