#-----------------------------------------------------------------------------
# NanoSoC Test: timer_driver_tests
# Timer driver validation tests
#-----------------------------------------------------------------------------
TESTNAME      := timer_driver_tests
SOURCE_DIR     = $(SOFTWARE_DIR)/common/validation
SOURCE_FILES  += $(DEVICE_DIR)/Source/CMSDK_driver.c

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
