#-----------------------------------------------------------------------------
# NanoSoC Test: self_reset_demo
# Self-reset mechanism demonstration
#-----------------------------------------------------------------------------
TESTNAME   := self_reset_demo
SOURCE_DIR  = $(SOFTWARE_DIR)/common/demos

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
