#-----------------------------------------------------------------------------
# NanoSoC Test: self_reset_demo
# Self-reset mechanism demonstration
#-----------------------------------------------------------------------------
TESTNAME   := self_reset_demo
SOURCE_DIR  = $(SOFTWARE_DIR)/common/demos

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
