#-----------------------------------------------------------------------------
# NanoSoC Test: adc_tests
# ADC peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := adc_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
