#-----------------------------------------------------------------------------
# NanoSoC Test: timer_tests
# Timer peripheral validation tests
#-----------------------------------------------------------------------------
TESTNAME   := timer_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
