#-----------------------------------------------------------------------------
# NanoSoC Test: apb_mux_tests
# APB multiplexer validation tests
#-----------------------------------------------------------------------------
TESTNAME           := apb_mux_tests
SOURCE_DIR          = $(SOFTWARE_DIR)/common/validation
GNU_CC_EXTRA_FLAGS := -flto

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
