#-----------------------------------------------------------------------------
# NanoSoC Test: dataio_tests
# Data I/O interface tests
#-----------------------------------------------------------------------------
TESTNAME        := dataio_tests
EXTRA_INCLUDES  += -I $(SOFTWARE_DIR)/drivers
SOURCE_FILES    += $(TEST_DIR)/dataio_functions.c
CC_EXTRA_FLAGS  := -Ospace

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
