#-----------------------------------------------------------------------------
# NanoSoC Test: dualtimer_demo
# Dual-timer peripheral demonstration
#-----------------------------------------------------------------------------
TESTNAME   := dualtimer_demo
SOURCE_DIR  = $(SOFTWARE_DIR)/common/demos

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
