#-----------------------------------------------------------------------------
# NanoSoC Software Compilation Makefile 
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright (C) 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
# Description:
# This Makefile generates the bootrom files for NanoSoC. This has been separated out
# of the software compilation makefile for simplicity.
#-----------------------------------------------------------------------------

#------------------------------------------------------------------------
# Read the AutoConfig Overloaded Variables
#------------------------------------------------------------------------
include $(SOCLABS_PROJECT_DIR)/autoconfig
export TOOL_CHAIN

# Software make options
# - Pass onto the software makefile to define targetted CPU type
# You can append additional make options for testcode here
SW_MAKE_OPTIONS = CPU_PRODUCT=CORTEX_M0 TOOL_CHAIN=$(TOOL_CHAIN)

# Bootrom Parameters:
# Boot Loader image
BOOTLOADER        ?= bootloader
BOOTROM_ADDRW     ?= 8
BOOTROM_HEX       ?= $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/testcodes/bootloader/$(BOOTLOADER).hex
BOOTROM_BUILD_DIR ?= $(SOCLABS_PROJECT_DIR)/system/src/bootrom

# Boot ROM generation
#--------------------------------------------------------------------------------
# Output files and directories
BOOTROM_SV_DIR  := $(BOOTROM_BUILD_DIR)/verilog
BOOTROM_BIN_DIR := $(BOOTROM_BUILD_DIR)/bintxt

# Output files
BOOTROM_SV      := $(BOOTROM_SV_DIR)/bootrom.sv
BOOTROM_BIN     := $(BOOTROM_BIN_DIR)/bootrom.bintxt

BOOTROM_SIM_DIR := $(SIM_TOP_DIR)/bootloader
BOOTROM_SIM_HEX := $(BOOTROM_SIM_DIR)/$(BOOTLOADER).hex

# Intermediate files
BOOTLOADER_HEX := $(TESTCODES_DIR)/$(BOOTLOADER)/$(BOOTLOADER).hex
BOOTROM_GEN_PY := $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/testcodes/bootloader/bootrom_gen.py

bootrom: $(BOOTROM_SV) $(BOOTROM_BIN) $(BOOTROM_SIM_HEX)

# Generate the Boot ROM Verilog and Binary Text files from the bootloader hex file
$(BOOTROM_SV) $(BOOTROM_BIN): $(BOOTROM_HEX) $(BOOTROM_GEN_PY) | $(BOOTROM_SV_DIR) $(BOOTROM_BIN_DIR)
	@echo "Generating Boot ROM Verilog and Binary Text files"
	@echo "Toolchain: $(TOOL_CHAIN)"
	@python3 $(BOOTROM_GEN_PY) -a $(BOOTROM_ADDRW) -i $(BOOTROM_HEX) -t $(TOOL_CHAIN) -v $(BOOTROM_SV) -b $(BOOTROM_BIN)

# Copy the bootloader hex file to the simulation directory
$(BOOTROM_SIM_HEX): $(BOOTLOADER_HEX) | $(SIM_TOP_DIR)/bootloader
	@echo "Copying Boot ROM hex file to simulation directory"
	@cp $(BOOTLOADER_HEX)  $(BOOTROM_SIM_HEX)

# Create output directories if they do not exist
$(BOOTROM_SV_DIR) $(BOOTROM_BIN_DIR) $(BOOTROM_SIM_DIR):
	@mkdir -p $@

# Compile bootloader in the testcodes/bootloader directory
$(BOOTROM_HEX):
	$(MAKE) -C $(TESTCODES_DIR)/$(BOOTLOADER) all_$(TOOL_CHAIN) $(SW_MAKE_OPTIONS)

# Target to remove bootrom build directory
clean:
	@echo "Removing Bootrom Build Directory"
	@rm -rf $(BOOTROM_BUILD_DIR)
	@echo "Removing Bootrom Simulation Directory"
	@rm -rf $(BOOTROM_SIM_DIR)
