#-----------------------------------------------------------------------------
# NanoSoC Test: gpio_driver_tests
# GPIO driver validation tests
#-----------------------------------------------------------------------------
TESTNAME      := gpio_driver_tests
SOURCE_DIR     = $(SOFTWARE_DIR)/common/validation
SOURCE_FILES  += $(DEVICE_DIR)/Source/CMSDK_driver.c

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
