#-----------------------------------------------------------------------------
# NanoSoC Test: snps_pvt_tests
# Synopsys PVT sensor validation tests
#-----------------------------------------------------------------------------
TESTNAME   := snps_pvt_tests
SOURCE_DIR  = $(SOFTWARE_DIR)/common/validation

include $(SOCLABS_NANOSOC_FIRMWARE_TECH_DIR)/build/testcode.mk
