#-----------------------------------------------------------------------------
# SoCLabs NanoSoC Discovery Table Verification Test
#
# Reads the auto-generated bus topology discovery registers at 0x4000_D000
# (APB slot 13) and verifies every field against expected values derived
# from the generated discovery YAML.
#
# The discovery table is generated by the soc_model discovery backend from
# the interconnect description.  The RDL is compiled to RTL by peakrdl-
# regblock and mapped into the SoC peripheral APB mux.
#
# Contributors
#   David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright 2024-6, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------

import struct
import sys
import os

import cocotb

from nanosoc_cocotb_driver import NanoSoC

# Add generated discovery map to Python path
sys.path.insert(0, os.path.join(
    os.environ.get("SOCLABS_PROJECT_DIR", ""),
    "build", "rtl", "nanosoc_combined_address_map", "address_maps",
))

# ---------------------------------------------------------------------------
# Discovery table base address (APB slot 13 in soc_peripheral region)
# ---------------------------------------------------------------------------
DISCOVERY_BASE = 0x4000D000

# ---------------------------------------------------------------------------
# Expected register values (from nanosoc_ahb_interconnect_discovery.yaml)
# These are the hardcoded reset values baked into the peakrdl-regblock RTL.
# ---------------------------------------------------------------------------

# Header
TABLE_MAGIC   = 0x534F4344  # "SOCD" in little-endian ASCII
TABLE_VERSION = 0x00000001
# TABLE_SIZE: num_targets=7, num_initiators=4, addr_width=32
TABLE_SIZE    = 0x00200407
# INTERCONNECT_NAME: "nano" packed little-endian
IC_NAME       = 0x6F6E616E

# Per-target descriptors: (name_str, base, size, attr, name_packed)
TARGETS = [
    ("cpu_ss",         0x00000000, 0x20000000, 0x00000041, 0x5F757063),
    ("soc_peripheral", 0x40000000, 0x10000000, 0x00010032, 0x5F636F73),
    ("dmac_ctrl",      0x50000000, 0x10000000, 0x00020032, 0x63616D64),
    ("exp",            0x60000000, 0x20000000, 0x00030032, 0x00707865),
    ("sram_0",         0x80000000, 0x00010000, 0x00040041, 0x6D617273),
    ("sram_1",         0x90000000, 0x00010000, 0x00050041, 0x6D617273),
    ("systable",       0xF0000000, 0x00040000, 0x00060012, 0x74737973),
]

# Per-initiator descriptors: (name_str, name_packed, visibility_mask)
INITIATORS = [
    ("cpu_0",  0x5F757063, 0x0000007E),
    ("debug",  0x75626564, 0x0000007F),
    ("dmac_0", 0x63616D64, 0x0000003B),
    ("dmac_1", 0x63616D64, 0x0000003B),
]

# Attribute field decoders (for human-readable logging)
REGION_TYPES = {0: "unknown", 1: "memory", 2: "periph", 3: "debug"}
SW_ACCESS    = {0: "none", 1: "ro", 2: "wo", 3: "rw", 4: "rwx"}


def decode_name(packed: int) -> str:
    """Unpack a 4-char little-endian ASCII name from a 32-bit integer."""
    return struct.pack("<I", packed).decode("ascii").rstrip("\x00")


def decode_attr(attr: int) -> str:
    """Format attribute register fields for logging."""
    rtype = REGION_TYPES.get(attr & 0xF, "?")
    access = SW_ACCESS.get((attr >> 4) & 0xF, "?")
    tid = (attr >> 16) & 0xFF
    return f"type={rtype}, access={access}, id={tid}"


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@cocotb.test()
async def test_discovery_header(dut):
    """Verify the discovery table header registers (magic, version, size,
    interconnect name) match the expected auto-generated values."""

    soc = NanoSoC(dut)
    await soc.start()

    failures = []

    checks = [
        ("TABLE_ID",          DISCOVERY_BASE + 0x000, TABLE_MAGIC),
        ("TABLE_VERSION",     DISCOVERY_BASE + 0x004, TABLE_VERSION),
        ("TABLE_SIZE",        DISCOVERY_BASE + 0x008, TABLE_SIZE),
        ("INTERCONNECT_NAME", DISCOVERY_BASE + 0x00C, IC_NAME),
    ]

    for name, addr, expected in checks:
        val = await soc.read32(addr)
        if val == expected:
            extra = ""
            if name == "INTERCONNECT_NAME":
                extra = f' ("{decode_name(val)}")'
            dut._log.info(f"  PASS  {name}: 0x{val:08X}{extra}")
        else:
            msg = f"  FAIL  {name} @ 0x{addr:08X}: got 0x{val:08X}, expected 0x{expected:08X}"
            dut._log.error(msg)
            failures.append(msg)

    assert not failures, "\n".join(failures)
    dut._log.info("Discovery header checks PASSED")


@cocotb.test()
async def test_discovery_targets(dut):
    """Read all target descriptors from the discovery table and verify
    base address, size, attributes, and name fields."""

    soc = NanoSoC(dut)
    await soc.start()

    failures = []

    # First verify we can read the number of targets
    table_size = await soc.read32(DISCOVERY_BASE + 0x008)
    num_targets = table_size & 0xFF
    assert num_targets == len(TARGETS), (
        f"NUM_TARGETS mismatch: got {num_targets}, expected {len(TARGETS)}"
    )

    for i, (tgt_name, exp_base, exp_size, exp_attr, exp_name_packed) in enumerate(TARGETS):
        offset = 0x010 + (i * 16)

        base_val = await soc.read32(DISCOVERY_BASE + offset + 0x0)
        size_val = await soc.read32(DISCOVERY_BASE + offset + 0x4)
        attr_val = await soc.read32(DISCOVERY_BASE + offset + 0x8)
        name_val = await soc.read32(DISCOVERY_BASE + offset + 0xC)

        dut._log.info(
            f"  Target {i} ({tgt_name}): base=0x{base_val:08X} "
            f"size=0x{size_val:08X} attr=0x{attr_val:08X} "
            f'name="{decode_name(name_val)}"'
        )

        for field, got, exp in [
            (f"TGT_{i}_BASE", base_val, exp_base),
            (f"TGT_{i}_SIZE", size_val, exp_size),
            (f"TGT_{i}_ATTR", attr_val, exp_attr),
            (f"TGT_{i}_NAME", name_val, exp_name_packed),
        ]:
            if got != exp:
                msg = f"  FAIL  {field}: got 0x{got:08X}, expected 0x{exp:08X}"
                dut._log.error(msg)
                failures.append(msg)

    assert not failures, "\n".join(failures)
    dut._log.info(f"All {len(TARGETS)} target descriptors PASSED")


@cocotb.test()
async def test_discovery_initiators(dut):
    """Read all initiator descriptors from the discovery table and verify
    name and visibility bitmask fields."""

    soc = NanoSoC(dut)
    await soc.start()

    failures = []

    # Initiator descriptors start after target descriptors
    init_base_offset = 0x010 + (len(TARGETS) * 16)

    for j, (init_name, exp_name_packed, exp_visibility) in enumerate(INITIATORS):
        offset = init_base_offset + (j * 8)

        name_val = await soc.read32(DISCOVERY_BASE + offset + 0x0)
        vis_val  = await soc.read32(DISCOVERY_BASE + offset + 0x4)

        # Decode visibility mask for logging
        visible_targets = []
        for t in range(len(TARGETS)):
            if vis_val & (1 << t):
                visible_targets.append(TARGETS[t][0])

        dut._log.info(
            f'  Initiator {j} ({init_name}): name="{decode_name(name_val)}" '
            f"visibility=0x{vis_val:08X} -> {visible_targets}"
        )

        for field, got, exp in [
            (f"INIT_{j}_NAME", name_val, exp_name_packed),
            (f"INIT_{j}_VISIBILITY", vis_val, exp_visibility),
        ]:
            if got != exp:
                msg = f"  FAIL  {field}: got 0x{got:08X}, expected 0x{exp:08X}"
                dut._log.error(msg)
                failures.append(msg)

    assert not failures, "\n".join(failures)
    dut._log.info(f"All {len(INITIATORS)} initiator descriptors PASSED")


@cocotb.test()
async def test_discovery_cross_check_address_map(dut):
    """Cross-check discovery table target entries against the generated
    Python address map model to verify consistency between the two
    generated artifacts.

    The discovery table is generated from the YAML system description by
    the discovery backend, while the Python address map is generated by
    the address-map backend.  This test confirms they agree.
    """
    from nanosoc_address_map import ADDRESS_MAP, TARGETS as ADDR_MAP_TARGETS

    soc = NanoSoC(dut)
    await soc.start()

    failures = []

    # Read number of targets from discovery table
    table_size = await soc.read32(DISCOVERY_BASE + 0x008)
    num_targets = table_size & 0xFF

    for i in range(num_targets):
        offset = 0x010 + (i * 16)
        base_val = await soc.read32(DISCOVERY_BASE + offset + 0x0)
        name_val = await soc.read32(DISCOVERY_BASE + offset + 0xC)
        tgt_name_short = decode_name(name_val)

        # Find matching region in address map (debug initiator view)
        region = ADDRESS_MAP.resolve(base_val, initiator="debug")

        if region is None:
            dut._log.warning(
                f"  Discovery target {i} ({tgt_name_short}) @ 0x{base_val:08X} "
                f"not found in address map"
            )
            continue

        dut._log.info(
            f"  Target {i}: discovery base=0x{base_val:08X} "
            f"matches address map region '{region.target}' "
            f"[0x{region.base:08X}-0x{region.end:08X}]"
        )

    assert not failures, "\n".join(failures)
    dut._log.info("Discovery / address-map cross-check PASSED")
