#-----------------------------------------------------------------------------
# NanoSoC Test: dma_tests
# DMA controller (PL230) validation tests
#-----------------------------------------------------------------------------
TESTNAME    := dma_tests
SOURCE_DIR   = $(SOFTWARE_DIR)/common/validation
USE_GENERIC := 1

include $(SOCLABS_NANOSOC_ARCH_TECH_DIR)/firmware/build/testcode.mk
